using System;
using System.Collections.Generic;
using System.Text;

namespace Wrapper.Database
{
    public class GatherableTypes
    {
        public static List<string> FishingSpots = new List<string>()
        {      
            "Schooner Wreckage",
            "Deep Sea Monsterbelly School",
            "Floating Wreckage",
            "Highland Mixed School",
            "Waterlogged Wreckage",
            "Dragonfin Angelfish School",
            "Musselback Sculpin School",
            "Glacial Salmon School",
            "Moonglow Cuttlefish School",
            "Steam Pump Flotsam",
            "School of Darter",
            "Bloodsail Wreckage",
            "Bluefish School",
            "Fangtooth Herring School",
            "Abyssal Gulper School",
            "Mudfish School",
            "Borean Man O' War School",
            "Brackish Mixed School",
            "Nettlefish School",
            "Jawless Skulker School",
            "Albino Cavefish School",
            "Giant Mantis Shrimp Swarm",
            "Glassfin Minnow School",
            "Elysian Thade School",
            "Blind Lake Sturgeon School",
            "Sagefish School",
            "Fire Ammonite School",
            "Firefin Snapper School",
            "Oily Blackmouth School",
            "Imperial Manta Ray School",
            "Iridescent Amberjack School",
            "Blackwater Whiptail School",
            "Mixed Ocean School",
            "Sporefish School",
            "Jade Lungfish School",
            "Redbelly Mandarin School",
            "Jewel Danio School",
            "Tiger Gourami School",
            "Lagoon Pool",
            "Crowded Redbelly Mandarin",
            "Greater Sagefish School",
            "School of Deviate Fish",
            "Emperor Salmon School",
            "Large Pool of Crowded Redbelly Mandarin",
            "Pool of Fire",
            "Reef Octopus Swarm",
            "Sea Scorpion School",
            "Fat Sleeper School",
            "Shipwreck Debris",
            "Great Sea Catfish School",
            "Pure Water",
            "Floating Debris",
            "Deepsea Sagefish School",
            "Silvergill Pike School",
            "Spinefin Piranha School",
            "Fathom Eel Swarm",
            "Shimmering Whorl",
            "Hyper-Compressed Ocean",
            "Large Pool of Glimmering Jewel Danio",
            "Slimy Mackerel School",
            "Blackbelly Mudfish School",
            "Cursed Queenfish School",
            "Highland Guppy School",
            "Krasarang Paddlefish School",
            "Brew Frenzied Emperor Salmon",
            "Ghostly Queenfish School",
            "Glimmering Jewel Danio Pool",
            "Glowing Jade Lungfish",
            "School of Golden Minnows",
            "Shipwreck Debris",
            "Strange Pool",
            "Tangled Mantis Shrimp Cluster",
            "Black Barracuda School",
            "Felmouth Frenzy School",
            "Mountain Trout School",
            "Stonescale Eel Swarm",
            "U'taka School",
            "Huge Fever of Stormrays",
            "Ionized Minnows",
            "Large Swarm of Migrated Reef Octopus",
            "Oily Abyssal Gulper School",
            "Pocked Bonefish School",
            "Pool of Blood",
            "Shipwreck Debris",
            "Sparkling Pool",
            "Large Pool of Glowing Jade Lungfish",
            "Lively Highmountain Salmon School",
            "Viper Fish School",
            "Fever of Stormrays",
            "Lane Snapper School",
            "Lively Mossgill Perch School",
            "Rasboralus School",
            "Sand Shifter School",
            "Savage Piranha Pool",
            "Sha-Touched Spinefish",
            "Swarm of Panicked Paddlefish",
            "Tiragarde Perch School",
            "Frenzied Pool",
            "Huge Mossgill Perch School",
            "Large Tangled Mantis Shrimp Cluster",
            "Oily Sea Scorpion School",
            "Roiling Whirlpool",
            "Sentry Fish School",
            "Spinefish School",
            "Aberrant Voidfin School",
            "Felmouth Frenzy School",
            "Floating Garbage",
            "Frenzied Fish",
            "Frenzied Fish",
            "Huge Cursed Queenfish School",
            "Huge Cursed Queenfish School",
            "Huge Fever of Stormrays",
            "Huge Fever of Stormrays",
            "Huge Highmountain Salmon School",
            "Huge Mossgill Perch School",
            "Huge Runescale Koi School",
            "Huge Runescale Koi School",
            "Large Pool of Sha-Touched Spinefish",
            "Large Swarm of Panicked Paddlefish",
            "Lively Cursed Queenfish School",
            "Lively Cursed Queenfish School",
            "Lively Highmountain Salmon School",
            "Lively Mossgill Perch School",
            "Lively Runescale Koi School",
            "Lively Runescale Koi School",
            "Lively Stormray School",
            "Malformed Gnasher School",
            "Mauve Stinger School",
            "Oodelfjiskenpool",
            "Redtail Loach School",
            "Runescale Koi School",
            "Wild Northern Barracuda School",
            "Albino Barracuda School",
            "Blue Barracuda School",
            "Crane Yolk Pool",
            "Frenzied Fangtooth School",
            "Frenzied Fish",
            "Highmountain Salmon School",
            "Huge Cursed Queenfish School",
            "Huge Highmountain Salmon School",
            "Huge Mossgill Perch School",
            "Huge Runescale Koi School",
            "Large Pool of Brew Frenzied Emperor Salmon",
            "Large Pool of Tiger Gourami Slush",
            "Lively Cursed Queenfish School",
            "Lively Highmountain Salmon School",
            "Lively Mossgill Perch School",
            "Lively Stormray School",
            "Lost Sole School",
            "Submarine Tar",
            "Swarm of Migrated Reef Octopus",
            "Tiger Gourami Slush",
            "Bubble-Eyed Rolly School",
            "Lively Runescale Koi School",
            "Mossgill Perch School",
            "Shipwreck Debris"
        };

        public static List<string> HerbNames = new List<string>() {
                "Anchor Weed", "Draenic Seeds", "Stranglekelp", "Purple Lotus", "Wildvine",
                "Zin'anthid", "Ancient Lichen", "Goldthorn", "Frost Lotus", "Peacebloom",
                "Yseralline Seed", "Silverleaf", "Aethril", "Whiptail", "Siren's Pollen",
                "Sea Stalk", "Earthroot", "Foxflower", "Briarthorn", "Sungrass",
                "Cinderbloom", "Kingsblood", "Stormvine", "Nightmare Vine",
                "Adder's Tongue", "Wild Steelbloom", "Firebloom", "Mageroyal",
                "Golden Sansam", "Star Moss", "Astral Glory", "Mountain Silversage",
                "Marrowroot", "Vigil's Torch", "Rising Glory", "Death Blossom",
                "Nightshade", "Ground Death Blossom", "Ground Nightshade",
                "Ground Widowbloom", "Starlight Rose", "Ground Marrowroot",
                "Ground Rising Glory", "Golden Lotus", "Ground Vigil's Torch",
                "Azshara's Veil", "Flame Cap", "Fel Lotus", "Felwort", "Black Lotus",
                "Grave Moss", "Mana Thistle", "Netherbloom", "Talandra's Rose",
                "Winter's Kiss", "Dreamleaf", "Liferoot", "Felweed", "Lichbloom",
                "Gorgrond Flytrap", "Riverbud", "Dreaming Glory", "Swiftthistle",
                "Arthas' Tears", "Ghost Mushroom", "Gromsblood", "Terocone", "Fire Leaf",
                "Dreamfoil", "Sorrowmoss", "Khadgar's Whisker", "Blindweed",
                "Akunda's Bite", "Goldclover", "Heartblossom", "Green Tea Leaf", "Fadeleaf",
                "Bruiseweed", "Icethorn", "Starflower", "Twilight Jasmine", "Deadnettle",
                "Ragveil", "Dragon's Teeth", "Frostweed", "Fool's Cap", "Icecap",
                "Fjarnskaggl", "Snow Lily", "Fireweed", "Nagrand Arrowbloom",
                "Talador Orchid", "Tiger Lily", "Rain Poppy", "Felwort Seed", "Silkweed",
                "Blood Elf", "Bloodthistle", "Rising Glory Petal", "Starlight Rose Seed",
                "Broken Frostweed Stem", "Starflower Petal", "Nagrand Arrowbloom Petal",
                "Rain Poppy Petal", "Talador Orchid Petal", "Dreamleaf Seed",
                "Whiptail Stem", "Fire Leaf Bramble", "Broken Fireweed Stem",
                "Heartblossom Petal", "Ancient Lichen Petal", "Marrowroot Petal",
                "Gorgrond Flytrap Ichor", "Felweed Stalk", "Purple Lotus Petal",
                "Nightshade Petal", "Death Blossom Petal", "Silkweed Stem",
                "Golden Sansam Leaf", "Liferoot Stem", "Aethril Seed", "Foxflower Seed",
                "Torn Green Tea Leaf", "Dreamfoil Blade", "Goldthorn Bramble",
                "Talandra's Rose Petal", "Fadeleaf Petal", "Widowbloom Petal",
                "Mana Thistle Leaf", "Bloodvine", "Fjarnskaggl Seed", "Nightmare Vine Stem",
                "Icecap Petal", "Firebloom Petal", "Fool's Cap Spores", "Stormvine Stalk",
                "Cinderbloom Petal", "Ragveil Cap", "Wild Steelbloom Petal",
                "Earthroot Stem", "Vigil's Torch Petal", "Snow Lily Petal",
                "Azshara's Veil Stem", "Lichbloom Stalk", "Sungrass Stalk",
                "Twilight Jasmine Petal", "Dragon's Teeth Stem", "Kingsblood Petal",
                "Bruiseweed Stem", "Nightmare Seed", "Goldclover Leaf", "Sorrowmoss Leaf",
                "Ghost Mushroom Cap", "Grave Moss Leaf", "Icethorn Bramble",
                "Swiftthistle Leaf", "Nightshade"
            };

        public static List<string> OreNames = new List<string>() {
                "Cobalt Deposit", "Titanium Vein", "Silver Vein", "Khorium Vein",
                "Adamantite Deposit", "Mithril Deposit", "Fel Iron Deposit", "Iron Deposit",
                "Saronite Deposit", "Tin Vein", "Obsidium Deposit", "Rich Thorium Vein",
                "Copper Vein", "Elethium Deposit", "Truesilver Deposit", "Elementium Vein",
                "Trillium Vein", "Oxxein Deposit", "Gold Vein", "Solenium Deposit",
                "Laestrite Deposit", "Phaedrum Deposit", "Rich Cobalt Deposit",
                "Sinvyr Deposit", "Rich Elethium Deposit", "Rich Saronite Deposit",
                "Pyrite Deposit", "Rich Adamantite Deposit", "Small Thorium Vein",
                "Phaedrum Deposit", "Dark Iron Deposit", "Pure Saronite Deposit",
                "Rich Sinvyr Deposit", "Rich Solenium Deposit", "Rich Laestrite Deposit",
                "Rich Obsidium Deposit", "Ancient Gem Vein", "Rich Oxxein Deposit",
                "Rich Elementium Vein", "Rich Trillium Vein", "Leystone Deposit",
                "Rich Adamantite Deposit", "Felslate Deposit", "Monelite Deposit",
                "Ghost Iron Deposit", "Platinum Deposit", "Rich Phaedrum Deposit",
                "Kyparite Deposit", "Storm Silver Deposit", "Nethercite Deposit",
                "Tin Vein", "Felslate Seam", "Brimstone Destroyer Core", "Leystone Seam",
                "Rich Pyrite Deposit", "Rich Ghost Iron Deposit", "True Iron Deposit",
                "Ooze Covered Thorium Vein", "Rich Felslate Deposit",
                "Brimstone Destroyer Core", "Brimstone Destroyer Core",
                "Ooze Covered Rich Thorium Vein", "Harvestable Precious Crystal",
                "Smoldering True Iron Deposit", "True Iron Deposit", "Azure Ore",
                "Burnished Platinum Deposit", "Rich Leystone Deposit",
                "Rich True Iron Deposit", "Luminous Monelite Deposit", "Shiny Stones",
                "Brimstone Destroyer Core", "Copper Vein", "Monelite Seam",
                "Rich Storm Silver Deposit", "Incendicite Mineral Vein",
                "Blackrock Deposit", "Empyrium Seam", "Hardened Monelite Deposit",
                "Blackrock Deposit", "Rich True Iron Deposit", "Brimstone Destroyer Core",
                "Gleaming Storm Silver Deposit", "Luminous Monelite Deposit",
                "Storm Silver Seam", "Trillium Vein", "Coarse Storm Silver Deposit",
                "Dense Storm Silver Deposit", "Empyrium Deposit", "Rich Empyrium Deposit",
                "Chrysoberyl Outcropping", "Felslate Spike",
                "Gleaming Storm Silver Deposit", "Large Obsidian Chunk",
                "Rich Kyparite Deposit", "Rich Monelite Deposit", "Rich Trillium Vein",
                "Small Obsidian Chunk", "Brimstone Destroyer Core",
                "Primordial Felslate Deposit", "Rich Platinum Deposit",
                "Superior Leystone Deposit", "Alterac Granite",
                "Burnished Platinum Deposit", "Copper Vein", "Enchanted Earth",
                "Osmenite Seam", "Rich Blackrock Deposit", "Rich Blackrock Deposit",
                "Rough Monelite Deposit", "Secreted Wax Glob", "True Iron Deposit",
                "True Iron Deposit", "Ooze Covered Silver Vein",
                "Ooze Covered Iron Deposit", "Rich Thorium Vein",
                "Black Blood of Yogg-Saron", "Brimstone Destroyer Core",
                "Brimstone Destroyer Core", "Rich True Iron Deposit",
                "Lesser Bloodstone Deposit", "Indurium Mineral Vein",
                "Brimstone Destroyer Core", "Coarse Leystone Outcropping", "Copper Vein",
                "Fine Leystone Deposit", "Massive Leystone Deposit",
                "Rich Ghost Iron Deposit", "Blackrock Deposit", "Brimstone Destroyer Core",
                "Brimstone Destroyer Core", "Brimstone Destroyer Core",
                "Burning Felslate Deposit", "Chrysoberyl Outcropping",
                "Dense Leystone Outcropping", "Fiery Leystone Deposit",
                "Gleaming Leystone Outcropping", "Luminous Sinvyr Deposit",
                "Ooze Covered Truesilver Deposit", "Primal Leystone Outcropping",
                "Rich Osmenite Deposit", "Rich True Iron Deposit",
                "Shattered Felslate Seam", "Stormy Leystone Deposit",
                "Warm Leystone Deposit", "Ooze Covered Gold Vein",
                "Rich Adamantite Deposit", "Rich Adamantite Deposit", "Blackrock Deposit",
                "Brimstone Destroyer Core", "Brimstone Destroyer Core",
                "Brimstone Destroyer Core", "Charged Leystone Deposit",
                "Chrysoberyl Outcropping", "Chunk of Saronite", "Darkened Felslate Deposit",
                "Ductile Platinum Deposit", "Enchanted Earth", "Exquisite Leystone Deposit",
                "Ghost Iron Deposit", "Hardened Leystone Outcropping",
                "Hardened Monelite Deposit", "Heavy Felslate Deposit",
                "Odious Felslate Outcropping", "Osmenite Deposit",
                "Radiant Leystone Outcropping", "Rich Blackrock Deposit",
                "Rich Trillium Vein", "Sapphire of Aku'Mai", "Smooth Platinum Deposit",
                "Strange Ore", "Striking Leystone Deposit", "Wild Leystone Seam",
                "Iron Deposit", "Iron Deposit", "Gold Vein", "Ooze Covered Mithril Deposit",
                "Titanium Node", "Ancient Leystone Deposit", "Bright Leystone Deposit",
                "Brilliant Leystone Seam", "Coarse Storm Silver Deposit",
                "Crude Leystone Seam", "Dark Leystone Deposit", "Draenethyst Mine Crystal",
                "Ductile Platinum Deposit", "Glowing Leystone Deposit",
                "Hard Leystone Deposit", "Krasari Iron", "Kyparite Deposit",
                "Luminous Leystone Outcropping", "Magnificent Leystone Deposit",
                "Malevolent Felslate Outcropping", "Needles Iron Pyrite",
                "Nethervine Crystal", "Raw Leystone Seam", "Rich Energized Iron",
                "Rich Kyparite Deposit", "Rough Leystone Outcropping",
                "Smooth Leystone Deposit", "Smooth Platinum Deposit", "The Light of Souls",
                "Tin Vein", "Truesilver Deposit", "Arcanite Lode",
                "Ooze Covered Arcanite Lode", "Saronite Deposit", "Obsidium Deposit",
                "Rich Saronite Deposit", "Dense Storm Silver Deposit", "Iron Deposit",
                "Mining Node Point Check", "Rough Monelite Deposit",
            };

    }
}
